import {dataStuct} from '../app/components/add-sheet/add-sheet';

export const dataStucts: dataStuct[] = [
    {"ID":1,  
    "Inventory":2,
    "Title":"aa",
    "AmazonListingPrice":5,
    "SupplierName":"aa", 
    "SupplierPrice":3,
    "AmazonFee":4,
    "Taxes":5,
    "ShippingFee":6,    
    "Profit":7,
    "ProfitMargin":9,
    "Status":false,
    "AmazonUrl":"aa",
    "SupplierUrl":"hhs",
    "Note":true},
    {"ID":2,  
    "Inventory":2,
    "Title":"aa",
    "AmazonListingPrice":5,
    "SupplierName":"aa", 
    "SupplierPrice":3,
    "AmazonFee":4,
    "Taxes":5,
    "ShippingFee":6,    
    "Profit":7,
    "ProfitMargin":9,
    "Status":true,
    "AmazonUrl":"aa",
    "SupplierUrl":"hhs",
    "Note":false}
  ];