import {HandsondataInt, dataStuct} from '../app/components/add-sheet/add-sheet';


export const Handsondat: HandsondataInt[] = [
  //  [
  //  {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // }
  
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": "",
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": "",
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": "",
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": "",
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": "",
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": "",
  // }
];


export const dataStucts: dataStuct[] = [
  {
    Id:"",
    SheetName: "",
    Date: new Date(new Date().setDate(new Date().getDate() + 0)),
    Notes: "",
    Ongoing: true,
    Handsondata: Handsondat,
    LastupdatedBy:"",
    createdBy:"",
    LastUpdateDate:new Date(new Date().setDate(new Date().getDate() + 0))
      
}
]