import {HandsondataInt, dataStuct} from '../app/components/add-sheet/add-sheet';


export const Handsondat: HandsondataInt[] = [
  //  [
  //  {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // }
  
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": "",
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": "",
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": "",
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": "",
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": "",
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": ""
  // },
  // {
  //   "Inventory": 0,
  //   "Title": "",
  //   "AmazonListingPrice": 0,
  //   "SupplierName": "",
  //   "SupplierPrice": 0,
  //   "AmazonFee": 0,
  //   "Taxes": 0,
  //   "ShippingFee": 0,
  //   "Profit": 0,
  //   "ProfitMargin": 0,
  //   "AmazonUrl": "",
  //   "SupplierUrl": "",
  // }
];


export const dataStucts: dataStuct[] = [
  {
    sheetId:"",
    sheetName: "",
    sheetDate: new Date(new Date().setDate(new Date().getDate() + 0)),
    sheetNotes: "",
    active: true,
    Handsondata: Handsondat,
    updated:new Date(new Date().setDate(new Date().getDate() + 0)),
    updatedBy:"",
    createdBy:"",
    created:new Date(new Date().setDate(new Date().getDate() + 0))
      
}
]